"""Catalog fixtures sync — bootstrap wiring (CAT-3, docs/catalog-fixtures-sync.md).

The monolith ships a demo catalog as the canon in ``fixtures/catalog/``
(``features.json`` / ``categories.json`` + the ``.sync-state.json`` sidecar),
generated by the real ``export_catalog`` command off ORM-seeded data — never
hand-written (round-trip is only guaranteed via the export path). This test
pins the contract ``bootstrap.sh`` relies on:

- a clean DB + ``load_catalog --seed-if-empty`` materializes that catalog;
- bootstrapping an already-seeded DB is a pure no-op (idempotent, per the
  ``load_staff_group_if_empty`` precedent this flag mirrors);
- re-running the *regular* (non-seed) reconciliation against unchanged
  fixtures also writes nothing (§6 invariant #2);
- re-exporting after a seed reproduces the committed fixtures byte-for-byte
  (§6 invariant #3 — round-trip stability).
"""
import filecmp
import os

import pytest
from django.conf import settings
from django.core.management import call_command

from stapel_categories import catalog_load as cl
from stapel_categories.models import Category, Feature

FIXTURES_DIR = os.path.join(str(settings.BASE_DIR), "fixtures", "catalog")

EXPECTED_CATEGORY_SLUGS = {"electronics", "phones", "laptops", "home-appliances"}


@pytest.mark.django_db
class TestCatalogBootstrapSeed:
    def test_seed_if_empty_loads_the_committed_catalog(self):
        assert not Category.objects.exists()
        assert not Feature.objects.exists()

        report = cl.load_catalog(FIXTURES_DIR, seed_if_empty=True)

        assert not report.failed
        assert report.count(cl.CREATED) > 0
        assert set(Category.objects.values_list("slug", flat=True)) == EXPECTED_CATEGORY_SLUGS
        # 3 shared root features + 2 category-local overrides (phones: color, warranty_months).
        assert Feature.objects.filter(tn_parent__isnull=True).count() == 3
        assert Feature.objects.filter(tn_parent__isnull=False).count() == 2

    def test_seed_if_empty_is_a_no_op_on_an_already_populated_catalog(self):
        cl.load_catalog(FIXTURES_DIR, seed_if_empty=True)
        cat_count = Category.objects.count()
        feat_count = Feature.objects.count()

        report = cl.load_catalog(FIXTURES_DIR, seed_if_empty=True)

        assert report.count(cl.CREATED) == 0
        assert report.count(cl.UPDATED) == 0
        assert report.count(cl.DELETED) == 0
        assert Category.objects.count() == cat_count
        assert Feature.objects.count() == feat_count

    def test_regular_reload_of_unchanged_fixtures_writes_nothing(self):
        """Idempotency invariant (§6.2): a second, *non*-seed reconciliation
        against a DB that already matches the fixtures is zero saves, zero
        revision bumps — not just the --seed-if-empty short-circuit."""
        cl.load_catalog(FIXTURES_DIR, seed_if_empty=True)

        report = cl.load_catalog(FIXTURES_DIR)

        assert not report.failed
        assert report.count(cl.CREATED) == 0
        assert report.count(cl.UPDATED) == 0
        assert report.count(cl.DELETED) == 0

    def test_reexport_after_seed_is_byte_identical_to_the_committed_fixtures(self, tmp_path):
        """Round-trip stability (§6.3): export(load(F)) == F."""
        cl.load_catalog(FIXTURES_DIR, seed_if_empty=True)

        call_command("export_catalog", out=str(tmp_path))

        for name in ("features.json", "categories.json"):
            committed = os.path.join(FIXTURES_DIR, name)
            regenerated = os.path.join(str(tmp_path), name)
            assert filecmp.cmp(committed, regenerated, shallow=False), (
                f"{name} drifted after a clean seed -> re-export round-trip"
            )
